FROM python:3.9
WORKDIR /app

COPY ./flask-server/ ./flask-server/requirements.txt ./flask-server/app.py ./flask-server/.flaskenv ./flask-server/models.py ./flask-server/controller.py ./flask-server/test.db ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]
