version: "3"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
  client:
    restart: always
    depends_on:
    - api
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"